### ISSUE TITLE
Incorrect Mobile Number Example

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/rms-website#34]
On the https://rms.stats4sd.org/ page, I click ‘subscribe for updates’.
In "WhatsApp number" field, the description shows an incorrect mobile phone number example:
1. There should be no zero after country code 44
2. The last part should be 6 digits instead of 7 digits

--- 

Screen shot

![image](https://github.com/stats4sd/rms-website/assets/86968034/2c786d19-9187-4914-bb97-ca81427573af)

**Comment by emilynevitt** [comment]
Forms edited accordingly.
